---
title: "MARS"
output: html_notebook
author: Deepika Dilip
---

```{r}
knitr::opts_chunk$set(echo=TRUE)
knitr::opts_chunk$set(warning=F)
knitr::opts_chunk$set(message=F)
```

```{r}
library(tidyverse) 
library(ggplot2)
library(janitor)
library(earth)
library(pdp)
library(readxl)
library(caret)
```

#Importing Data
```{r}
taipei_data <- read_excel("Real_estate_valuation_data_set.xlsx") %>%
  janitor::clean_names()
```

#Selecting x and y
```{r}
taipei_data <- na.omit(taipei_data) 
taipei_data$no <- NULL

x <- model.matrix(y_house_price_of_unit_area~. ,taipei_data)[,-1]
y <- taipei_data$y_house_price_of_unit_area
```

#Optimizing Tuning Parameters (caret package)
```{r}
set.seed(2)
mars_grid <- expand.grid(degree = 1:2, nprune = 2:8)
ctrl1 <- trainControl(method = "cv", number = 10)

mars.fit <- train(x, y, method = "earth", tuneGrid = mars_grid, trControl = ctrl1)

ggplot(mars.fit)

print(mars.fit$bestTune)
print(coef(mars.fit$finalModel))
```

##Degree = 1, Prune no. = 6
## RMSE:7.624305 
## R-Squared: 0.6960429
##MAE: 5.241945

#PDP for MARS
```{r}
par(mfrow=c(3,2))

print(mars.fit[["finalModel"]][["namesx"]])
partial(mars.fit, pred.var = c("x1_transaction_date"), grid.resolution = 10) %>% autoplot()
partial(mars.fit, pred.var = c("x2_house_age"), grid.resolution = 10) %>% autoplot()
partial(mars.fit, pred.var = c("x3_distance_to_the_nearest_mrt_station"), grid.resolution = 10) %>% autoplot()
partial(mars.fit, pred.var = c("x4_number_of_convenience_stores"), grid.resolution = 10) %>% autoplot()
partial(mars.fit, pred.var = c("x5_latitude"), grid.resolution = 10) %>% autoplot()
partial(mars.fit, pred.var = c("x6_longitude"), grid.resolution = 10) %>% autoplot()

```
